name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          mkdir -p /tmp/test
          echo hello > /tmp/test/world.txt

      - name: Test artifact
        uses: actions/upload-artifact@v2
        with:
          name:test-txt
          path: /tmp/test/world.txt
