name: Test

on:
  push:
    branches:
      - main

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo hello > world.txt
          cat world.txt

      - name: Test artifact
        uses: actions/upload-artifact@v2
        with:
          name: world.txt
          path: ${{ github.workspace }}

  test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          cat world.txt
