name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"

      - name: check date
        run: |
          echo ${date}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create key pem
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.KEY_FILE_PW }}" --output key.pem test-key.pem.gpg
          chmod 400 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@35.74.213.136 exit
          echo $?
